// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gAE5dtigfxTIWt4iDFPTJu0gojjTdbI',
    appId: '1:673751060520:web:e3dab10fa8819b1480e51d',
    messagingSenderId: '673751060520',
    projectId: 'fluttersample-b6a1d',
    authDomain: 'fluttersample-b6a1d.firebaseapp.com',
    storageBucket: 'fluttersample-b6a1d.appspot.com',
    measurementId: 'G-CCK37SP0ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxaEPclNwkRP347rHfYRqh7XjwMXIuvKU',
    appId: '1:673751060520:android:0d86b92ffe8d8dd480e51d',
    messagingSenderId: '673751060520',
    projectId: 'fluttersample-b6a1d',
    storageBucket: 'fluttersample-b6a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vQd_FsA9-UX0GwZRU5pO5ESfC2SNUHQ',
    appId: '1:673751060520:ios:b23f097d55c2207380e51d',
    messagingSenderId: '673751060520',
    projectId: 'fluttersample-b6a1d',
    storageBucket: 'fluttersample-b6a1d.appspot.com',
    iosClientId: '673751060520-n0th2ii8j11oe3f34eg73sjelctmd94k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vQd_FsA9-UX0GwZRU5pO5ESfC2SNUHQ',
    appId: '1:673751060520:ios:fa2621572ced748080e51d',
    messagingSenderId: '673751060520',
    projectId: 'fluttersample-b6a1d',
    storageBucket: 'fluttersample-b6a1d.appspot.com',
    iosClientId: '673751060520-ot8ab2vuhjkcccd9qbo9lu554ledolku.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication17.RunnerTests',
  );
}
